FROM ubuntu:22.04
LABEL maintainer="Morgan Askins <maskins@berkeley.edu>"

SHELL ["/bin/bash", "-c"]

ARG MAKE_JOBS=""

RUN apt-get -q update \
 && DEBIAN_FRONTEND=noninteractive apt-get -qy install --no-install-recommends \
    git curl build-essential vim libx11-dev libxpm-dev qt6-base-dev libqt6opengl6-dev ssh cmake \
    xserver-xorg-video-intel libxft-dev libxext-dev libxerces-c-dev \
    libxkbcommon-x11-dev libopengl-dev libgl1-mesa-dev python3 python3-dev python3-numpy \
    libcurl4-gnutls-dev ca-certificates libssl-dev libffi-dev libgsl-dev \
    libfftw3-dev pkg-config libtbb-dev \
 && apt-get autoclean \
 && apt-get clean

RUN useradd -ms /bin/bash ratuser

WORKDIR /

RUN git clone https://github.com/rat-pac/ratpac-setup.git
WORKDIR /ratpac-setup

RUN chown -R ratuser:ratuser /ratpac-setup
USER ratuser
RUN ./setup.sh --only root -j${MAKE_JOBS:-$(nproc)}
RUN ./setup.sh --only geant4 -j${MAKE_JOBS:-$(nproc)}
RUN ./setup.sh --only cry
ENV PATH=/ratpac-setup/local/bin:$PATH
RUN sed -i '1s/^/#!\/bin\/bash\n/' /ratpac-setup/env.sh
RUN printf '\nexec "$@"\n' >> /ratpac-setup/env.sh
RUN chmod +x env.sh

ENTRYPOINT ["/ratpac-setup/env.sh"]
CMD [ "/bin/bash" ]
